create table pos_intelig(
periodo varchar(100),
tipo varchar(100),
op varchar(100),
filial varchar(100),
valor_faturado varchar(100),
qtd_nfst integer,
total_vc2 decimal(12,2),
total_vc3 decimal(12,2),
total_vcinternacional decimal(12,2),
total_minutagem decimal(12,2),
qtd_chamadas decimal(12,2),
valor_arrecadado decimal(12,2),
valor_arrecadado_maior_75_dias decimal(12,2),
valor_contestado_arrecadado decimal(12,2),
valor_prestação_servico decimal(12,2),
valor_de_repasse decimal(12,2),
cpmf decimal(12,2),
juros_e_multas decimal(12,2),
valor_repasse_acertos decimal(12,2),
vl_bruto_arrecadado decimal(12,2),
aliq_impostos decimal(12,2),
vl_liquido_arrecadado decimal(12,2),
acertos decimal(12,2),
penalidades decimal(12,2),
tipo2 varchar(100)
);